"""
Script to run retraining and produce a CSV report and simple HTML report.
Saves: retrain_report.csv, model.joblib and docs/report.html
"""
import pandas as pd
from src.recommender import Recommender
from pathlib import Path
import datetime


def run(materials_path="data/sample_materials.csv", ratings_path="data/sample_ratings.csv"):
    materials = pd.read_csv(materials_path)
    ratings = pd.read_csv(ratings_path)
    rec = Recommender(alpha=0.6, n_components=10, random_state=42)
    rec.fit(materials, ratings)
    rec.save("model.joblib")
    report = {
        "n_materials": len(materials),
        "n_ratings": len(ratings),
        "n_users": int(ratings["user_id"].nunique()),
        "generated_at": datetime.datetime.utcnow().isoformat(),
    }
    Path("docs").mkdir(parents=True, exist_ok=True)
    pd.DataFrame([report]).to_csv("retrain_report.csv", index=False)
    # simple HTML
    html = f"""
    <html><head><meta charset="utf-8"><title>Retrain Report</title></head><body>
    <h1>Retrain Report</h1>
    <pre>{report}</pre>
    <p>Note: this file is generated by scripts/retrain.py</p>
    </body></html>
    """
    with open("docs/report.html", "w", encoding="utf-8") as fh:
        fh.write(html)
    print("Retrain finished. Files: retrain_report.csv, model.joblib, docs/report.html")


if __name__ == "__main__":
    run()